<a href="https://colab.research.google.com/github/VISHAL4411835/DataScienceProject/blob/main/ANN_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANN CLASSIFIER

**Importing Library**

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
tf.__version__

'2.4.1'

# Data Preprocessing

**Improting Dataset**

In [ ]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
x = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

In [ ]:
print(x)

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1              

**OneHotEncoding**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x[1,:])

[0.0 0.0 1.0 608 'Female' 41 1 83807.86 1 0 1 112542.58]


**Label Encoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 4] = le.fit_transform(x[:, 4])

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Spliting Train test dataset**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 0)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [ ]:
print(np.array(y_train))

[0 0 0 ... 0 0 1]


In [ ]:
print(np.array(y_test))

[0 1 0 ... 0 0 0]


**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [ ]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# ANN MODEL

Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

**Adding First Hidden Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

**Adding Second Hidden Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

**Adding Output Layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN Model

**Compiling the ANN**

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Train the ANN**

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6353 - accuracy: 0.6626
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4792 - accuracy: 0.7976
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4478 - accuracy: 0.7941
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8151
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3935 - accuracy: 0.8355
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3864 - accuracy: 0.8393
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3703 - accuracy: 0.8414
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3581 - accuracy: 0.8500
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3507 - accuracy: 0.8533
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3615 - accura

# Model Testing

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: 50000

So, should we say goodbye to that customer?

In [ ]:
print(ann.predict(sc.transform([[0,0,1,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_pred,y_test)

[[1527   68]
 [ 202  203]]


0.865